### ISSUE TITLE
filter old trac entries

### ISSUE THREAD

**Issue by ltiessen** [pmarkowski/toggl-api-frontend#1]
When I go to pick a task from dotNET it first lists a whole bunch of numbers that got imported from track. Maybe filter out all tasks that only consist of numbers? I don't want to see those.

**Comment by pmarkowski** [comment]
Going to see about getting those tasks marked as inactive, and put in a filter on inactive tasks from appearing in the drop down.

**Comment by pmarkowski** [comment]
Closing this, these tickets no longer appear.
